### ISSUE TITLE
Python3 KivMob

### ISSUE THREAD

**Issue by John0000000** [MichaelStott/KivMob#5]
Hi,
Can we use KivMob with Python3?
Thanks

**Comment by MichaelStott** [comment]
That is a good question... this has only been tested with Python3....

**Comment by MichaelStott** [comment]
It has only been tested with Python2. When I last checked, Python3 Android support was still in an experimental stage. I'll try building a Python3 APK sometime soon to test.

**Comment by ivanadam** [comment]
Hi,
can you please explain what has to be done to build a python3 apk with kivmob?

Thanks in advance

**Comment by MichaelStott** [comment]
For those still interested, this _should_ technically be possible now with the latest buildozer update but I'm still encountering build issues with python3. Will update when I know more.

**Comment by MichaelStott** [comment]
The issue I'm currently encountering is with importing the run_on_ui_thread decorator from the android module. It doesn't appear compatible with python 3. I'll try to create a PR/fix for this.

**Comment by Huyston** [comment]
I could successfully compile an APK that shows and interstitial with python3 (the example code). However it only works if I press the button 2 times, and then it doesn't show anymore.

**Comment by MichaelStott** [comment]
@Huyston Thanks, that's good to hear. The example code in the README doesn't automatically request another interstitial ad after the button is pressed, which is why it only shows up once. Not sure why you would need to press the button twice in this instance.

I'll try building the example code with Python 3 later this week. If it's successful, I'll update the CI tests and add Python 3 as officially supported in the README.

**Comment by MichaelStott** [comment]
Now added:  https://github.com/MichaelStott/KivMob/pull/40
