### ISSUE TITLE
Getting 'AndroidBridge' object has no attribute '_interstitial' error while using real admob ids

### ISSUE THREAD

**Issue by tanishqborkar** [MichaelStott/KivMob#85]
I was not getting this error when using TestAds but upon using real admob ids there was this error coming .Pls tell me about a potential fix for this

**Comment by akgupta0777** [comment]
Please add Your code I am here to help you.
Let me see where you are doing mistake. I can't understand your problem without looking at the code.

Send the Error logs .

Error logs are something like this 
Error : Traceback Most recent call last …

**Comment by tanishqborkar** [comment]
Here are the code Screenshots:
![mainApp](https://user-images.githubusercontent.com/63917472/94558251-57ac2880-027d-11eb-978b-d3a0501077b9.png)
![request](https://user-images.githubusercontent.com/63917472/94558287-6397ea80-027d-11eb-92f5-bbb926213787.png)
![InAppTry](https://user-images.githubusercontent.com/63917472/94558299-67c40800-027d-11eb-812b-8bc2dd8d0564.png)
![kvTry](https://user-images.githubusercontent.com/63917472/94558374-76aaba80-027d-11eb-98ab-372bd36e475e.png)
![requestKV](https://user-images.githubusercontent.com/63917472/94558417-7f02f580-027d-11eb-8b0a-ed8c2d213dab.png)


here are the logs

![Screenshot (48)](https://user-images.githubusercontent.com/63917472/94558587-ae196700-027d-11eb-8b4c-cb3f1b191fbb.png)

**Comment by akgupta0777** [comment]
@tanishqborkar  By looking at the logs It seems that in your code there is something related to any variable or object named **MobileAds**  and I can't see anything in your code that shows information about **MobileAds** . 
So please include that code.

Also please attach the full buildozer.spec file also.

It seems that you are trying to run your app on your phone via command

`buildozer android deploy`.

Try converting to APK first by using command 

`buildozer android debug`
And then install APK on your phone.

And Feel free to ask help because we are here for you.

**Comment by MichaelStott** [comment]
MobileAds is a package in AdMob that isn't being instantiated for some reason. The only two reasons I can think of for this would be either AndroidBridge was never instantiated by KivMob or you are missing the AdMob library in buildozer.spec.

**Comment by akgupta0777** [comment]
@MichaelStott  Thanks for pointing the reference.
I also thinks that @tanishqborkar didn't add the KivMob library in buildozer.spec requirements section This is a common mistake most beginners do.

So @tanishqborkar please show us your buildozer.spec or add KivMob in your requirements in buildozer.spec

Please report here in comments .if this will not works so that we will fix issues in KivMob (if any).

**Comment by tanishqborkar** [comment]
The error is solved . I had not mentioned the gradle dependencies and android meta data in buildozer spec file.Now my App is published and shows ads too...Thank You for such an outstanding initiative of  implementing ads in kivy......

**Comment by akgupta0777** [comment]
Thanks for your kind words. Please close the issue if your problem is solved.
